### ISSUE TITLE
Make linux-headers-amd64 dependency optional

### ISSUE THREAD

**Issue by morfikov** [Whonix/lkrg#2]
I'm using a custom debian kernel and when I've built the deb package and wanted to install it, I got the following:

```
# aptitude install lkrg-dkms
The following NEW packages will be installed:
  linux-compiler-gcc-9-x86{a} linux-headers-5.6.0-2-amd64{a} linux-headers-5.6.0-2-common{a}
  linux-headers-amd64{a} linux-kbuild-5.6{a} lkrg-dkms
```

Wouldn't be better to change the following:
`Depends: linux-headers-amd64 [linux-amd64] | linux-headers-generic,`
to 
`Recommends:  linux-headers-amd64 [linux-amd64] | linux-headers-generic,`
in order to support custom kernels without the need to install the Debian kernels?

**Comment by adrelanos** [comment]
Mikhail Morfikov:
> I'm using a custom debian kernel


And the build process doesn't produce a `linux-headers-amd64` package?
Or any other generic header package name similar to `linux-headers-amd64`?

If not, another alternative would be to create a dummy
linux-headers-amd64 meta package to fulfill the dependency.

> Wouldn't be better to change the following:
> `Depends: linux-headers-amd64 [linux-amd64] | linux-headers-generic,`
> to 
> `Recommends:  linux-headers-amd64 [linux-amd64] | linux-headers-generic,`


It's really a `Depends:`. Without kernel headers installed package
installation will fail during DKMS.

According to
https://www.cyberciti.biz/faq/debian-10-set-up-wireguard-vpn-server/
please see this image
https://www.cyberciti.biz/media/new/faq/2020/04/Debian-10-install-WireGuard-using-apt-or-apt-get-command.png

Looks like "sudo apt install wireguard" somehow results in installation
of `linux-headers-amd64`. Why's that?

Any Debian policy on that subject?

**Comment by morfikov** [comment]
Yes, the kernel headers are needed, but in this config it wants to install the `linux-headers-amd64`, which is a standard debian package that pulls `linux-headers-5.6.0-2-amd64` . If the kernel changes, then `linux-headers-amd64` will pull some other `linux-headers-*-amd64` package. Usually, everyone, who has kernel installed, also has some kernel headers installed. So to cover both cases (the debian kernel and some custom one), you shouldn't put `linux-headers-amd64` as dependency -- it should be optional (recomended) to cover the debian case, but to cover the other cases, a user shouldn't be forced to install any of the debian kernel packages.

There are many `*-dkms` packages in debian -- look at their dependencies. I just checked a few of them, and none of them has any kernel headers related packages included in their dependencies. They usually depend on `dkms` , and the `dkms` package has:

`Recommends: ... linux-headers-686-pae | linux-headers-amd64 | linux-headers-generic | linux-headers`

And that is enough to build the dkms modules, as in most installations the recommended dependencies are installed by default.

**Comment by morfikov** [comment]
Wouldn't be better to rely on the `dkms` package like other `*-dkms` modules do? In this way the `dkms` dependency would simply take care off any stuff needed to compile the module.

Check for instance [the wireguard module](https://packages.debian.org/pl/sid/wireguard-dkms)
